services:
  api:
    build: .
    container_name: artist_management_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=artist_management
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    restart: always
  
  static:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    container_name: static_server
    volumes:
      - ./app:/app
      - ./static:/app/static
    command: uvicorn static_server:app --host 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    restart: always

  postgres:
    image: postgres:14-alpine
    container_name: artist_management_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=artist_management
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
